<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-U5FT8QJ" ignored="3" name="Test(failed)" tests="2" failures="2" timestamp="2022-11-04T16:52:30 IST" time="0.118" errors="0">
  <testcase name="Test5" time="0.023" classname="TestNGDemo.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNGDemo.TestDemo.Test5(TestDemo.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test5 -->
  <testcase name="Test4" time="0.003" classname="TestNGDemo.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNGDemo.TestDemo.Test4(TestDemo.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test4 -->
  <testcase name="Test2" time="0.0" classname="TestNGDemo.TestDemo">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.0" classname="TestNGDemo.TestDemo">
    <ignored/>
  </testcase> <!-- Test3 -->
  <testcase name="Test1" time="0.0" classname="TestNGDemo.TestDemo">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Test(failed) -->
